[versions]
minecraft = "1.21.11"
bstats = "3.1.0"
shadow = "9.3.0"
run-paper = "3.0.2"

[libraries]
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
